import React from "react";

export const CodeIcon = () => {
  return (
    <svg
      width="32px"
      height="32px"
      id="Layer_1"
      version="1.1"
      viewBox="0 0 128 128"
    >
      <g>
        <g>
          <g>
            <line
              fill="none"
              stroke="#f6cb42"
              stroke-width="8"
              stroke-linecap="square"
              stroke-miterlimit="10"
              x1="34.033"
              x2="8.566"
              y1="89.467"
              y2="64"
            />
            <line
              fill="none"
              stroke="#f6cb42"
              stroke-width="8"
              stroke-linecap="square"
              stroke-miterlimit="10"
              x1="8.566"
              x2="34.033"
              y1="64"
              y2="38.533"
            />
          </g>
          <g>
            <line
              fill="none"
              stroke="#f6cb42"
              stroke-width="8"
              stroke-linecap="square"
              stroke-miterlimit="10"
              x1="93.967"
              x2="119.434"
              y1="38.533"
              y2="64"
            />
            <line
              fill="none"
              stroke="#f6cb42"
              stroke-width="8"
              stroke-linecap="square"
              stroke-miterlimit="10"
              x1="119.434"
              x2="93.967"
              y1="64"
              y2="89.467"
            />
          </g>
        </g>
        <line
          fill="none"
          stroke="#f6cb42"
          stroke-width="8"
          stroke-linecap="square"
          stroke-miterlimit="10"
          x1="42"
          x2="87.561"
          y1="105.621"
          y2="22.379"
        />
      </g>
    </svg>
  );
};
