import Head from "next/head";
import { Banner } from "../components/Banner/Banner";
import { ColorBar } from "../components/ColorBar/ColorBar";
import { Footer } from "../components/Footer/Footer";
import { Form } from "../components/Form/Form";
import { Information } from "../components/Information-Banner/Information-Banner";
import { Services } from "../components/Services/Services.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dixcode Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dixcode-logo-azul.svg" />
        <link
          href="https://fonts.googleapis.com/css?family=Sarabun:400,500,600,700|Rubik:300,400,500"
          rel="stylesheet"
        />
      </Head>

      <Banner />
      <Information />
      <Services />
      <ColorBar/>
      <Form/>
      <Footer/>
    </>
  );
}
